# Aula 3 - Python for Data Engineer
# Arquivo de configuração para analisar o impacato dos artigos
---
TITLE: OVERVIEW
KEYWORDS: characteristics
ABSTRACT: 
YEAR: 
TYPE_PUBLICATION: 
DOI: 
JCR_VALUE: 
SCIMAGO_VALUE: 
FORMATO: CSV
...