# Aula 3 - Python for Data Engineer
# Arquivo de configuração para analisar o impacato dos artigos
---
TITLE: OVERVIEW
KEYWORDS: characteristics
ABSTRACT: C
YEAR: D
TYPE_PUBLICATION: E
DOI: F
JCR_VALUE: G
SCIMAGO_VALUE: H
FORMATO: CSV
...