# Aula 3 - Python for Data Engineer
# Arquivo de configuração para analisar o impacato dos artigos
---
TITLE: Big Data
KEYWORDS: 
ABSTRACT: 
YEAR: 
TYPE_PUBLICATION: 
DOI: 
JCR_VALUE: 
SCIMAGO_VALUE: 2.082
FORMATO: CSV
...