# Aula 3 - Python for Data Engineer
# Arquivo de configuração para analisar o impacato dos artigos
---
TITLE: Big
KEYWORDS: Data
ABSTRACT: 
YEAR: 
TYPE_PUBLICATION: 
DOI: 
JCR_VALUE: 
SCIMAGO_VALUE: 27.083
FORMATO: CSV
...